Update fees.mdx
astroport-fi/docs pull request #10
Opened 2024-03-25 22:12 UTC by c0deNoodle

added info for PCL pool fees

2024-03-26 12:47 UTC, epanchee requested changes

2024-03-26 12:47 UTC, epanchee commented on docs/learn/astro-tokenomics/fees.mdx
> +- 2/3rds of the total fee goes to the LPs for the relevant pool — this remains denominated in the native pool tokens and acts as a payment by increasing the size of the pools (thus increasing the num
Fee is split 25% to xASTRO stakers and 75% to LPs on Osmosis and 50:50 on other outposts

2024-03-26 12:47 UTC, epanchee commented on docs/learn/astro-tokenomics/fees.mdx
> +For passive concentrated liquidity pools, this fee is variable and ranges from 0.26% to 0.45% (or 0.03% to 0.45% for some liquid staking pairs) divided as follows:
This fee is not strictly set by protocol and depends on instantiate params. It is indeed recommended as you mentioned but we have different settings, for example, in LUNA-BTC/ETH/SOL/BNB pairs on Terra (0.05%-0.30%) and (0.05%-0.20%) on Osmosis.

2024-03-26 18:38 UTC, c0deNoodle commented
Updated based on feedback from @epanchee. Thanks!

2024-03-30 10:41 UTC, epanchee approved these changes
LGTM

2024-10-28 07:53 UTC, merged